#! /usr/bin/env python3
from engine import EnigmaMachine
import sys

F_HELP = 'help.txt'

def main():
    arg_dict = arg_parse(sys.argv[1:])
    if arg_dict['help']:
        help_display()
        exit()
    
    if arg_dict['infile'] != None:#can possibly simplify
        arg_dict['message'] = infile_load(arg_dict['infile'])

    e = EnigmaMachine()
    translated_message = e.translate(arg_dict['message'], arg_dict['day'])

    if arg_dict['outfile'] != None:
        outfile_write(translated_message, arg_dict['outfile'])
    else:
        print(translated_message)

def arg_parse(args):
    arg_dict = {'infile' : None,
                'outfile' : None,
                'day' : 1,
                'verbose' : False,
                'help' : False,
                'message' : None}
    remaining_args = list(args)
    
    for arg, nextarg in zip(args, args[1:]+[""]):
        if arg[0] == '-':
            remaining_args.remove(arg)
            if arg in ['-i', '--infile']:
                arg_dict['infile'] = nextarg
                remaining_args.remove(nextarg)
            elif arg in ['-o', '--outfile']:
                arg_dict['outfile'] = nextarg
                remaining_args.remove(nextarg)
            elif arg in ['-d', '--day']:
                if int(nextarg) > 31 or int(nextarg) < 1:
                    print("ERROR 2: Day out of range [1, 31].")
                    exit()
                arg_dict['day'] = nextarg
                remaining_args.remove(nextarg)
            elif arg in ['-v', '--verbose']:
                arg_dict['verbose'] = True
            elif arg in ['-h', '--help']:
                arg_dict['help'] = True
    
    if len(remaining_args) == 1:
        arg_dict['message'] = remaining_args[0]
    elif len(remaining_args) == 0:
        arg_dict['message'] = None
    else:
        print("ERROR 1: Too many arguments.")
        exit()

    return arg_dict

def help_display():
    with open(F_HELP, 'r') as f:
        print(f.read())

def infile_load(path):
    try:
        with open(path, 'r') as f:
            message = f.read()
        return message
    except FileNotFoundError:
        print("ERROR 3: Infile does not exist.")
        exit()

def outfile_write(message, path):
    with open(path, 'w') as f:
        f.write(message)

if __name__ == '__main__':
    main()
